public enum Gender { MALE, FEMALE, UNSPECIFIED };
public enum UserRole { PEDESTRIAN, DRIVER };
public enum FavoriteIconNamesEnum { FAV_ICO_HOME, FAV_ICO_WORK, FAV_ICO_FLAG }
public enum TripState { ACTIVE, INACTIVE, CANCELED, ENDED };
public enum PedestrianJoinRequestState { REQUESTED, CANCELED, BOARDED, ACCEPTED, REJECTED, CANCELED_AFTER_ACCEPTED };
public enum LocationOperationType { GET_MY_ADDRESS, GET_ADDRESS, TRACK_LOCATION };
public enum PUSH_TYPE { PEDESTRIAN_REQUEST, DRIVER_RESPONSE, DRIVER_CANCELLED, PEDESTRIAN_CANCELLED, PEDESTRIAN_BOARDED, NEW_LOTTERY_TICKET_WON, NEW_SPONSOR };
public enum ESTORE_PRODUCTS { SERVICE_PRODUCT, LOTTERY, UNLIMITED_PASS, BP_FUEL };
public enum ESTORE_EMAIL_TEMPLATES { WEEL_AMAGUIZ_EMAIL, WEEL_PRODUCT_PURCHASE_EMAIL, WEEL_ZENPARK_EMAIL, WEEL_FUEL_CHECK_BPE_MAIL, WEEL_WONDER_BOX_EMAIL, WEEL_SPEEDY_EMAIL, ECO_DRIVING_LESSON, ONE_GREEN_TOMATO_TICKET, ONE_SUPER_SHUTTLE_TICKET };
public enum REQUEST_TYPE { GET_SURROUNDING_USERS, SEARCH_TRIP, GET_PARTNER_LOCATION, UPDATE_MY_LOCATION, GET_TRIP_STATUS, ALL };

